use serde_json::Value;

fn tauri_config() -> Value {
    serde_json::from_str(include_str!("../tauri.conf.json")).expect("tauri.conf.json is valid JSON")
}

fn default_capability() -> Value {
    serde_json::from_str(include_str!("../capabilities/default.json"))
        .expect("default capability is valid JSON")
}

fn generated_native_command_permissions() -> &'static str {
    include_str!("../permissions/autogenerated/native_runtime_capabilities.toml")
}

#[test]
fn clock_window_is_static_hidden_transparent_and_fixed_size() {
    let config = tauri_config();
    let windows = config["app"]["windows"]
        .as_array()
        .expect("app windows are configured");
    let clock = windows
        .iter()
        .find(|window| window["label"] == "main")
        .expect("main clock window is configured");

    assert_eq!(clock["url"], "index.html");
    assert_eq!(clock["visible"], false);
    assert_eq!(clock["decorations"], false);
    assert_eq!(clock["transparent"], true);
    assert_eq!(clock["resizable"], false);
    assert_eq!(clock["skipTaskbar"], true);
    assert_eq!(clock["width"], 220);
    assert_eq!(clock["height"], 88);
    assert_eq!(clock["minWidth"], clock["width"]);
    assert_eq!(clock["maxWidth"], clock["width"]);
    assert_eq!(clock["minHeight"], clock["height"]);
    assert_eq!(clock["maxHeight"], clock["height"]);
}

#[test]
fn settings_window_is_available_as_a_separate_local_entry() {
    let config = tauri_config();
    let windows = config["app"]["windows"]
        .as_array()
        .expect("app windows are configured");
    let settings = windows
        .iter()
        .find(|window| window["label"] == "settings")
        .expect("settings window is configured");

    assert_eq!(settings["url"], "settings.html");
    assert_eq!(settings["visible"], false);
    assert_eq!(settings["transparent"], false);
    assert_eq!(settings["decorations"], true);
}

#[test]
fn capability_boundary_exposes_only_local_events_and_approved_native_operations() {
    let capability = default_capability();
    let permissions = capability["permissions"]
        .as_array()
        .expect("capability permissions are configured");
    let permission_ids = permissions
        .iter()
        .map(|permission| permission.as_str().expect("permission ids are strings"))
        .collect::<Vec<_>>();

    assert_eq!(capability["local"], true);
    assert!(capability.get("remote").is_none());
    assert_eq!(
        capability["windows"],
        serde_json::json!(["main", "settings"])
    );
    assert_eq!(
        permission_ids,
        [
            "core:event:allow-listen",
            "core:event:allow-unlisten",
            "allow-native-runtime-capabilities"
        ]
    );
    assert!(!permission_ids.iter().any(|id| id.starts_with("store:")));
    assert!(!permission_ids.iter().any(|id| id.starts_with("fs:")));
    assert!(!permission_ids.iter().any(|id| id.starts_with("http:")));
    assert!(!permission_ids.iter().any(|id| id == &"core:default"));
    assert!(!permission_ids.iter().any(|id| id == &"core:window:default"));
}

#[test]
fn native_runtime_capability_permission_is_generated_from_build_manifest() {
    let permissions = generated_native_command_permissions();

    assert!(permissions.contains(r#"identifier = "allow-native-runtime-capabilities""#));
    assert!(permissions.contains(r#"commands.allow = ["native_runtime_capabilities"]"#));
}

#[test]
fn bundled_app_icon_is_available_for_window_bundle_and_tray_assets() {
    let config = tauri_config();

    assert_eq!(
        config["bundle"]["icon"],
        serde_json::json!(["icons/icon.ico"])
    );
    assert!(!include_bytes!("../icons/icon.ico").is_empty());
}
